const KEY_PREFIX='study-tracker-v5-';
const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
let focusTimer=null, focusRemaining=25*60;
const $=s=>document.querySelector(s);
const id=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+Math.random().toString(16).slice(2);
const today=()=>new Date().toISOString().slice(0,10);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmtDate=d=>new Date(d+'T00:00').toLocaleDateString('en-KE',{day:'numeric',month:'short',year:'numeric'});
const empty=m=>'<div class="empty">'+m+'</div>';
function seed(){return{
theme:'dark',view:'dashboard',
profile:{name:'',institution:'',city:'',program:'',avatar:''},
preferences:{notifications:true,reminderMinutes:15,syncEnabled:true,syncKey:''},
goals:{weeklyMinutes:300,semesterTargetMinutes:7200},
activeSemesterId:'',semesters:[],units:[],lessons:[],tasks:[],attendance:[],sessions:[],events:[],grades:[],notes:[],resources:[]
}}
function migrate(x){const s=seed();const out=Object.assign(s,x||{});['semesters','units','lessons','tasks','attendance','sessions','events','grades','notes','resources'].forEach(k=>{if(!Array.isArray(out[k]))out[k]=[]});out.profile=Object.assign(s.profile,x?.profile||{});out.preferences=Object.assign(s.preferences,x?.preferences||{});out.goals=Object.assign(s.goals,x?.goals||{});return out}
let state=null;
function storageKey(){return KEY_PREFIX+String(window.__STUDY_USER__?.id||'guest')}
function initializeApp(serverState){
  const raw=serverState||localStorage.getItem(storageKey());
  try{state=migrate(typeof raw==='string'?JSON.parse(raw):raw)}catch{state=seed()}
  if(window.__STUDY_USER__?.profile)state.profile=Object.assign(state.profile,window.__STUDY_USER__.profile);
  localStorage.setItem(storageKey(),JSON.stringify(state));
  render();
  scheduleLessonReminder();
}
window.addEventListener('study-auth-ready',e=>initializeApp(e.detail?.state||null));
function save(){if(!state)return;localStorage.setItem(storageKey(),JSON.stringify(state));queueSync()}
let syncTimer=null;
function queueSync(){if(!state||!state.preferences.syncEnabled||location.protocol==='file:')return;clearTimeout(syncTimer);syncTimer=setTimeout(syncToServer,700)}
async function syncToServer(){try{const headers={'Content-Type':'application/json'};const r=await fetch('/api/state',{method:'PUT',headers,body:JSON.stringify({state})});setSync(r.ok?'Synced':r.status===401?'Sync key required':'Server error')}catch{setSync('Local only')}}
async function pullFromServer(){try{const headers={};const r=await fetch('/api/state',{headers});if(!r.ok)throw new Error();const data=await r.json();state=migrate(data.state);localStorage.setItem(KEY,JSON.stringify(state));render();toast('Server state loaded');setSync('Synced')}catch{toast('Could not load server state');setSync('Local only')}}
async function checkBackend(){if(location.protocol==='file:'){setSync('Local only');return}try{const r=await fetch('/api/health');const x=await r.json();setSync(x.syncProtected?'Server • protected':'Server connected')}catch{setSync('Local only')}}
function setSync(t){const el=$('#syncStatus');if(el){el.textContent=t;el.className='sync-status '+(t==='Local only'?'offline':'online')}}
const activeSem=()=>state.semesters.find(s=>s.id===state.activeSemesterId)||state.semesters[0];
const units=()=>state.units.filter(x=>x.semesterId===state.activeSemesterId);
const lessons=()=>state.lessons.filter(x=>x.semesterId===state.activeSemesterId);
const unitName=uid=>state.units.find(u=>u.id===uid)?.name||'General';
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function openModal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden')}
$('#closeModal').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()}
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>setView(b.dataset.view));
$('#semesterSelect').onchange=e=>{state.activeSemesterId=e.target.value;save();render()}
$('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';save();applyTheme()}
function setView(v){state.view=v;save();document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#pageTitle').textContent=({dashboard:'Dashboard',timetable:'Timetable',calendar:'Calendar',units:'Units','tasks':'Tasks & Assessments',attendance:'Attendance',grades:'Grades',sessions:'Study Sessions',focus:'Focus Lab',notes:'Notes',resources:'Resources',analytics:'Analytics',semesters:'Semesters',settings:'Settings'})[v]||'Dashboard';render()}
function applyTheme(){document.body.dataset.theme=state.theme}
function renderSelect(){$('#semesterSelect').innerHTML=state.semesters.map(s=>'<option value="'+s.id+'" '+(s.id===state.activeSemesterId?'selected':'')+'>'+esc(s.name)+' • '+esc(s.year)+'</option>').join('')}
function card(a,b,c,cl=''){return '<article class="stat '+cl+'"><span>'+a+'</span><strong>'+b+'</strong><small>'+c+'</small></article>'}
function weeklyMinutes(){const cutoff=new Date();cutoff.setDate(cutoff.getDate()-6);const key=cutoff.toISOString().slice(0,10);return state.sessions.filter(s=>s.semesterId===state.activeSemesterId&&s.date>=key).reduce((a,s)=>a+Number(s.minutes||0),0)}
function nextLesson(){const now=new Date(),d=now.toLocaleDateString('en-US',{weekday:'long'}),mins=now.getHours()*60+now.getMinutes(),ls=lessons().map(l=>Object.assign({},l,{mi:Number(l.start.slice(0,2))*60+Number(l.start.slice(3))})).sort((a,b)=>a.mi-b.mi);return ls.find(l=>l.day===d&&l.mi>mins)||ls.find(l=>DAYS.indexOf(l.day)>DAYS.indexOf(d))||ls[0]}
function lessonHtml(l){return '<div class="lesson-card"><div class="time-big">'+l.start+'<small>to '+l.end+'</small></div><div><h3>'+esc(unitName(l.unitId))+'</h3><p>'+l.day+' • '+esc(l.room||'Room not set')+'</p></div><span class="pill">Reminder '+l.reminder+'m</span></div>'}
function taskHtml(t){return '<div class="list-row"><div><b>'+esc(t.title)+'</b><small>'+esc(unitName(t.unitId))+' • '+esc(t.type||'Task')+' • due '+fmtDate(t.due)+'</small></div><span class="tag">'+esc(t.type||'Task')+'</span></div>'}
function renderDashboard(){const ss=state.sessions.filter(s=>s.semesterId===state.activeSemesterId),total=ss.reduce((a,s)=>a+Number(s.minutes||0),0),open=state.tasks.filter(t=>t.semesterId===state.activeSemesterId&&t.status!=='done').length,nl=nextLesson(),up=state.tasks.filter(t=>t.semesterId===state.activeSemesterId&&t.due>=today()&&t.status!=='done').sort((a,b)=>a.due.localeCompare(b.due)).slice(0,4),wm=weeklyMinutes();return '<section class="hero"><div><span class="pill">PRUDEN TECHNOLOGIES • ACTIVE SEMESTER</span><h2>'+esc(activeSem().name)+' control center</h2><p>'+fmtDate(activeSem().start)+' → '+fmtDate(activeSem().end)+'. Your academic command center for classes, deadlines, attendance, grades and independent study.</p></div><button class="primary" onclick="quickTask()">＋ Add task</button></section><div class="stats">'+card('Units',units().length,'active semester')+card('Classes / week',lessons().length,'recurring lessons')+card('Study time',Math.floor(total/60)+'h '+total%60+'m',ss.length+' logged sessions')+card('Open work',open,String(wm)+' min studied in 7 days','accent')+'</div><div class="grid2"><section class="panel"><div class="panel-head"><h3>Next lesson</h3><button class="text-btn" onclick="setView(\\'timetable\\')">Timetable →</button></div>'+(nl?lessonHtml(nl):empty('No lessons scheduled.'))+'</section><section class="panel"><div class="panel-head"><h3>Upcoming work</h3><button class="text-btn" onclick="setView(\\'tasks\\')">Tasks →</button></div>'+(up.length?up.map(taskHtml).join(''):empty('No upcoming work.'))+'</section></div><section class="panel"><div class="panel-head"><h3>Weekly target</h3><span class="muted">'+wm+' / '+state.goals.weeklyMinutes+' min</span></div><div class="progress"><span style="width:'+Math.min(100,wm/state.goals.weeklyMinutes*100)+'%"></span></div></section><section class="panel"><div class="panel-head"><h3>Week at a glance</h3><span class="muted">Classes per day</span></div><div class="mini-week">'+DAYS.map(d=>'<div><b>'+d.slice(0,3)+'</b><span>'+lessons().filter(l=>l.day===d).length+'</span></div>').join('')+'</div></section>'}
function renderTimetable(){return '<div class="view-head"><div><p class="muted">Recurring weekly timetable</p><h2>'+esc(activeSem().name)+'</h2></div><button class="primary" onclick="addLesson()">＋ Add lesson</button></div><section class="timetable">'+DAYS.map(d=>'<div class="day-col"><div class="day-head">'+d+'<small>'+lessons().filter(l=>l.day===d).length+' classes</small></div>'+(lessons().filter(l=>l.day===d).sort((a,b)=>a.start.localeCompare(b.start)).map(l=>'<div class="lesson" onclick="editLesson(\\''+l.id+'\\')"><strong>'+esc(unitName(l.unitId))+'</strong><span>'+l.start+'–'+l.end+'</span><small>'+esc(l.room||'No room')+' • '+l.reminder+'m reminder</small></div>').join('')||'<div class="day-empty">Free</div>')+'</div>').join('')+'</section>'}
function renderUnits(){return '<div class="view-head"><div><p class="muted">Subjects, credits and self-study targets</p><h2>Units</h2></div><button class="primary" onclick="addUnit()">＋ Add unit</button></div><div class="cards">'+(units().map(u=>{const mins=state.sessions.filter(s=>s.semesterId===state.activeSemesterId&&s.subject===u.name).reduce((a,s)=>a+Number(s.minutes||0),0),pct=Math.min(100,u.targetMinutes?mins/u.targetMinutes*100:0);return '<article class="unit-card"><div class="unit-icon">'+esc(u.name.slice(0,2).toUpperCase())+'</div><h3>'+esc(u.name)+'</h3><p>'+esc(u.code||'No unit code')+' • '+esc(u.room||'Room not set')+'</p><small>'+lessons().filter(l=>l.unitId===u.id).length+' lessons/week'+(u.lecturer?' • '+esc(u.lecturer):'')+'</small><div class="progress"><span style="width:'+pct+'%"></span></div><small>'+mins+' / '+(u.targetMinutes||0)+' min self-study target</small><div><button class="text-btn" onclick="editUnit(\\''+u.id+'\\')">Edit</button> <button class="danger-text" onclick="deleteUnit(\\''+u.id+'\\')">Delete</button></div></article>'}).join('')||empty('No units yet.'))+'</div>'}
function renderTasks(){const ts=state.tasks.filter(t=>t.semesterId===state.activeSemesterId).sort((a,b)=>a.due.localeCompare(b.due));return '<div class="view-head"><div><p class="muted">Assignments, CATs, tests, exams, projects and revision</p><h2>Tasks & Assessments</h2></div><button class="primary" onclick="quickTask()">＋ Add task</button></div><section class="panel"><div class="task-filters"><span class="pill">'+ts.filter(t=>t.status!=='done').length+' open</span><span class="pill">'+ts.filter(t=>t.status==='done').length+' done</span></div>'+(ts.map(t=>'<div class="list-row task-row"><input type="checkbox" '+(t.status==='done'?'checked':'')+' onchange="toggleTask(\\''+t.id+'\\')"><div><b class="'+(t.status==='done'?'done':'')+'">'+esc(t.title)+'</b><small>'+esc(unitName(t.unitId))+' • '+esc(t.type)+' • due '+fmtDate(t.due)+(t.priority?' • '+esc(t.priority):'')+'</small></div><button class="danger-text" onclick="deleteTask(\\''+t.id+'\\')">Delete</button></div>').join('')||empty('No academic work added.'))+'</section>'}
function renderAttendance(){return '<div class="view-head"><div><p class="muted">Attendance health by unit</p><h2>Attendance</h2></div></div><div class="cards">'+units().map(u=>{const a=state.attendance.filter(x=>x.semesterId===state.activeSemesterId&&x.unitId===u.id),p=a.filter(x=>x.status==='present').length,l=a.filter(x=>x.status==='late').length,ab=a.filter(x=>x.status==='absent').length,total=a.length,rate=total?Math.round((p+l*.5)/total*100):0;return '<article class="unit-card"><h3>'+esc(u.name)+'</h3><div class="progress"><span style="width:'+rate+'%"></span></div><strong>'+rate+'%</strong><p>'+p+' present • '+l+' late • '+ab+' absent</p><button class="primary small" onclick="markAttendance(\\''+u.id+'\\')">＋ Mark class</button></article>'}).join('')+'</div>'}
function renderGrades(){const gs=state.grades.filter(g=>g.semesterId===state.activeSemesterId),avg=gs.length?Math.round(gs.reduce((a,g)=>a+(Number(g.score)/Number(g.max||100))*100,0)/gs.length):0;return '<div class="view-head"><div><p class="muted">Assessment record</p><h2>Grades</h2></div><button class="primary" onclick="addGrade()">＋ Add grade</button></div><div class="stats">'+card('Average',avg+'%','across recorded assessments')+card('Assessments',gs.length,'recorded')+card('Best',gs.length?Math.max(...gs.map(g=>Math.round(g.score/g.max*100)))+'%':'—','highest score')+'</div><section class="panel">'+(gs.map(g=>'<div class="list-row"><div><b>'+esc(g.name)+'</b><small>'+esc(unitName(g.unitId))+' • '+esc(g.type||'Assessment')+'</small></div><strong>'+g.score+'/'+g.max+' ('+Math.round(g.score/g.max*100)+'%)</strong><button class="danger-text" onclick="deleteGrade(\\''+g.id+'\\')">Delete</button></div>').join('')||empty('No grades yet.'))+'</section>'}
function renderSessions(){const ss=state.sessions.filter(s=>s.semesterId===state.activeSemesterId).sort((a,b)=>b.date.localeCompare(a.date)),total=ss.reduce((a,s)=>a+Number(s.minutes||0),0);return '<div class="view-head"><div><p class="muted">Independent study outside scheduled classes</p><h2>Study Sessions</h2></div><button class="primary" onclick="addSession()">＋ Log session</button></div><div class="stats">'+card('Total',Math.floor(total/60)+'h '+total%60+'m','this semester')+card('Sessions',ss.length,'logged blocks')+card('Average',ss.length?Math.round(total/ss.length)+' min':'0 min','per session')+card('Weekly',weeklyMinutes()+' min','last 7 days','accent')+'</div><section class="panel">'+(ss.map(s=>'<div class="list-row"><div><b>'+esc(s.subject)+'</b><small>'+esc(s.type)+' • '+fmtDate(s.date)+(s.note?' • '+esc(s.note):'')+'</small></div><strong>'+s.minutes+' min</strong><button class="danger-text" onclick="deleteSession(\\''+s.id+'\\')">Delete</button></div>').join('')||empty('No study sessions yet.'))+'</section>'}
function renderFocus(){const mm=String(Math.floor(focusRemaining/60)).padStart(2,'0'),ss=state.sessions.filter(s=>s.semesterId===state.activeSemesterId&&s.type==='Focus'),mins=ss.reduce((a,s)=>a+Number(s.minutes),0);return '<section class="focus-hero panel"><span class="pill">FOCUS LAB</span><h2>'+mm+':'+String(focusRemaining%60).padStart(2,'0')+'</h2><p>Deep-work timer for revision, coding, reading or assignments.</p><div class="focus-actions"><button class="primary" onclick="toggleFocus()">'+(focusTimer?'Pause':'Start')+'</button><button class="secondary" onclick="resetFocus()">Reset</button><button class="secondary" onclick="setFocus(50)">50 min</button><button class="secondary" onclick="setFocus(25)">25 min</button></div><small>'+mins+' focus minutes logged this semester</small></section><section class="panel"><h3>Focus workflow</h3><p class="muted">Choose one unit, silence distractions, work until the timer ends, then log the block automatically.</p><button class="primary" onclick="addSession(\\'Focus\\')">＋ Log focus block</button></section>'}
function renderNotes(){const ns=state.notes.filter(n=>n.semesterId===state.activeSemesterId).sort((a,b)=>b.updated.localeCompare(a.updated));return '<div class="view-head"><div><p class="muted">Class notes, revision notes and ideas</p><h2>Notes</h2></div><button class="primary" onclick="addNote()">＋ New note</button></div><div class="cards">'+(ns.map(n=>'<article class="unit-card"><span class="pill">'+esc(unitName(n.unitId))+'</span><h3>'+esc(n.title)+'</h3><p>'+esc(n.body.slice(0,150))+(n.body.length>150?'…':'')+'</p><small>'+fmtDate(n.updated.slice(0,10))+'</small><div><button class="text-btn" onclick="editNote(\\''+n.id+'\\')">Open</button> <button class="danger-text" onclick="deleteNote(\\''+n.id+'\\')">Delete</button></div></article>').join('')||empty('No notes yet.'))+'</div>'}
function renderResources(){const rs=state.resources.filter(r=>r.semesterId===state.activeSemesterId);return '<div class="view-head"><div><p class="muted">Useful links, references, videos and documents</p><h2>Resources</h2></div><button class="primary" onclick="addResource()">＋ Add resource</button></div><section class="panel">'+(rs.map(r=>'<div class="list-row"><div><b>'+esc(r.title)+'</b><small>'+esc(unitName(r.unitId))+' • '+esc(r.type||'Link')+'</small></div><a class="text-btn" href="'+esc(r.url)+'" target="_blank" rel="noopener">Open ↗</a><button class="danger-text" onclick="deleteResource(\\''+r.id+'\\')">Delete</button></div>').join('')||empty('No resources saved.'))+'</section>'}
function renderCalendar(){const ev=[...state.events.filter(e=>e.semesterId===state.activeSemesterId),...state.tasks.filter(t=>t.semesterId===state.activeSemesterId).map(t=>({id:t.id,date:t.due,title:t.title,type:t.type}))].sort((a,b)=>a.date.localeCompare(b.date));return '<div class="view-head"><div><p class="muted">Deadlines and academic events</p><h2>Calendar</h2></div><button class="primary" onclick="addEvent()">＋ Add event</button></div><section class="panel">'+(ev.map(e=>'<div class="calendar-item"><strong>'+fmtDate(e.date)+'</strong><div><b>'+esc(e.title)+'</b><small>'+esc(e.type||'Event')+'</small></div></div>').join('')||empty('No calendar events.'))+'</section>'}
function renderAnalytics(){const ss=state.sessions.filter(s=>s.semesterId===state.activeSemesterId),total=ss.reduce((a,s)=>a+Number(s.minutes||0),0),done=state.tasks.filter(t=>t.semesterId===state.activeSemesterId&&t.status==='done').length,all=state.tasks.filter(t=>t.semesterId===state.activeSemesterId).length,att=state.attendance.filter(a=>a.semesterId===state.activeSemesterId),present=att.filter(a=>a.status==='present').length,rate=att.length?Math.round(present/att.length*100):0;const byUnit=units().map(u=>{const m=ss.filter(s=>s.subject===u.name).reduce((a,s)=>a+Number(s.minutes||0),0);return '<div class="analytics-row"><span>'+esc(u.name)+'</span><strong>'+m+' min</strong><div class="progress"><span style="width:'+Math.min(100,m/Math.max(1,u.targetMinutes||1800)*100)+'%"></span></div></div>'}).join('');return '<div class="view-head"><div><p class="muted">Patterns across your semester</p><h2>Analytics</h2></div></div><div class="stats">'+card('Study time',Math.floor(total/60)+'h '+total%60+'m','logged this semester')+card('Task completion',all?Math.round(done/all*100)+'%':'—',done+' / '+all+' completed')+card('Attendance',rate+'%','present classes')+card('Semester target',Math.min(100,Math.round(total/state.goals.semesterTargetMinutes*100))+'%','study-time target','accent')+'</div><section class="panel"><div class="panel-head"><h3>Study effort by unit</h3><span class="muted">vs self-study target</span></div>'+byUnit+'</section>'}
function renderSemesters(){return '<div class="view-head"><div><p class="muted">Your academic history stays organized on this device</p><h2>Semesters</h2></div><button class="primary" onclick="addSemester()">＋ New semester</button></div><div class="cards">'+state.semesters.map(s=>'<article class="unit-card '+(s.id===state.activeSemesterId?'selected':'')+'"><span class="pill">'+esc(s.status||'planned')+'</span><h3>'+esc(s.name)+'</h3><p>'+esc(s.year)+' • '+fmtDate(s.start)+' → '+fmtDate(s.end)+'</p><button class="primary small" onclick="activateSemester(\\''+s.id+'\\')">'+(s.id===state.activeSemesterId?'Active':'Switch')+'</button></article>').join('')+'</div>'}
function renderSettings(){return '<section class="panel settings"><span class="pill">PRUDEN TECHNOLOGIES</span><h2>Your student profile</h2><div class="profile-editor"><div class="avatar-wrap">'+(state.profile.avatar?'<img class="avatar" src="'+esc(state.profile.avatar)+'" alt="Profile photo">':'<div class="avatar placeholder">P</div>')+'</div><label>Profile photo<input id="profilePhoto" type="file" accept="image/png,image/jpeg,image/webp" onchange="handleProfilePhoto(event)"><small>Image is resized locally before storage.</small></label></div><label>Username<input value="'+esc(window.__STUDY_USER__?.username||'')+'" disabled></label><label>Display name<input id="p_name" value="'+esc(state.profile.name)+'"></label><label>Institution<input id="p_inst" value="'+esc(state.profile.institution)+'"></label><label>City / location<input id="p_city" value="'+esc(state.profile.city)+'"></label><label>Program / course<input id="p_prog" value="'+esc(state.profile.program)+'"></label><label>Weekly study target (minutes)<input id="p_week" type="number" value="'+state.goals.weeklyMinutes+'"></label><label>Semester study target (minutes)<input id="p_sem" type="number" value="'+state.goals.semesterTargetMinutes+'"></label><label>Theme<select id="themeSetting"><option value="dark" '+(state.theme==='dark'?'selected':'')+'>Dark</option><option value="light" '+(state.theme==='light'?'selected':'')+'>Light</option></select></label><div class="settings-actions"><button class="secondary" onclick="saveSettings()">Save profile</button><button class="secondary" onclick="pullFromServer()">Reload cloud data</button><button class="secondary" onclick="requestNotifications()">Enable reminders</button><button class="secondary" onclick="exportData()">Export backup</button><label class="file-label">Import backup<input type="file" accept=".json" onchange="importData(event)"></label><button class="secondary" onclick="logout()">Sign out</button><button class="danger" onclick="resetAll()">Reset my data</button></div><p class="muted">Your academic data belongs to your account. Each student has separate profile and academic state.</p></section>'}
function render(){renderSelect();applyTheme();const views={dashboard:renderDashboard,timetable:renderTimetable,calendar:renderCalendar,units:renderUnits,tasks:renderTasks,attendance:renderAttendance,grades:renderGrades,sessions:renderSessions,focus:renderFocus,notes:renderNotes,resources:renderResources,analytics:renderAnalytics,semesters:renderSemesters,settings:renderSettings};$('#appView').innerHTML=(views[state.view]||renderDashboard)();checkBackend()}
function input(id,label,type,value=''){return '<label>'+label+'<input id="'+id+'" type="'+type+'" value="'+esc(value)+'"></label>'}
function select(id,label,options,value){return '<label>'+label+'<select id="'+id+'">'+options.map(o=>'<option value="'+esc(o.value||o)+'" '+((o.value||o)===value?'selected':'')+'>'+esc(o.label||o.value||o)+'</option>').join('')+'</select></label>'}
function addUnit(u){u=u||{};openModal(u.id?'Edit unit':'Add unit','<div class="form-grid">'+input('f_name','Unit name','text',u.name||'')+input('f_code','Unit code','text',u.code||'')+input('f_lect','Lecturer','text',u.lecturer||'')+input('f_room','Default room','text',u.room||'')+input('f_target','Self-study target (minutes)','number',u.targetMinutes||1800)+'</div><button class="primary" onclick="saveUnit(\\''+(u.id||'')+'\\')">Save unit</button>')}
function saveUnit(uid){const name=$('#f_name').value.trim();if(!name)return;const data={id:uid||id(),semesterId:state.activeSemesterId,name,code:$('#f_code').value.trim(),lecturer:$('#f_lect').value.trim(),room:$('#f_room').value.trim(),credits:0,targetMinutes:Number($('#f_target').value)||1800};if(uid)Object.assign(state.units.find(u=>u.id===uid),data);else state.units.push(data);save();closeModal();render();toast('Unit saved')}
function editUnit(i){addUnit(state.units.find(u=>u.id===i))}
function deleteUnit(i){if(confirm('Delete this unit and its lessons?')){state.units=state.units.filter(u=>u.id!==i);state.lessons=state.lessons.filter(l=>l.unitId!==i);save();render()}}
function addLesson(l){l=l||{};openModal(l.id?'Edit lesson':'Add lesson','<div class="form-grid">'+select('f_unit','Unit',units().map(u=>({value:u.id,label:u.name})),l.unitId||units()[0]?.id)+select('f_day','Day',DAYS,l.day||'Monday')+input('f_start','Start','time',l.start||'08:00')+input('f_end','End','time',l.end||'10:00')+input('f_room','Room','text',l.room||'')+input('f_reminder','Reminder (minutes)','number',l.reminder??state.preferences.reminderMinutes)+'</div><button class="primary" onclick="saveLesson(\\''+(l.id||'')+'\\')">Save lesson</button>'+(l.id?'<button class="danger" onclick="deleteLesson(\\''+l.id+'\\')">Delete lesson</button>':''))}
function saveLesson(i){const data={id:i||id(),semesterId:state.activeSemesterId,unitId:$('#f_unit').value,day:$('#f_day').value,start:$('#f_start').value,end:$('#f_end').value,room:$('#f_room').value,reminder:Number($('#f_reminder').value)||0};if(i)Object.assign(state.lessons.find(l=>l.id===i),data);else state.lessons.push(data);save();closeModal();render();toast('Timetable updated')}
function editLesson(i){addLesson(state.lessons.find(l=>l.id===i))}
function deleteLesson(i){state.lessons=state.lessons.filter(l=>l.id!==i);save();closeModal();render()}
function quickTask(){openModal('Add academic work','<div class="form-grid">'+input('f_title','Title','text','')+select('f_taskUnit','Unit',[{value:'',label:'General'},...units().map(u=>({value:u.id,label:u.name}))],'')+select('f_type','Type',['Assignment','CAT','Test','Exam','Project','Revision'],'Assignment')+select('f_priority','Priority',['Normal','High','Critical'],'Normal')+input('f_due','Due date','date',today())+'</div><button class="primary" onclick="saveTask()">Save task</button>')}
function saveTask(){const title=$('#f_title').value.trim();if(!title)return;state.tasks.push({id:id(),semesterId:state.activeSemesterId,title,unitId:$('#f_taskUnit').value,type:$('#f_type').value,priority:$('#f_priority').value,due:$('#f_due').value,status:'open'});save();closeModal();render();toast('Task added')}
function toggleTask(i){const t=state.tasks.find(x=>x.id===i);if(t){t.status=t.status==='done'?'open':'done';save();render()}}
function deleteTask(i){state.tasks=state.tasks.filter(x=>x.id!==i);save();render()}
function markAttendance(uid){openModal('Mark attendance','<p>'+esc(unitName(uid))+' • '+fmtDate(today())+'</p><div class="attendance-buttons"><button onclick="saveAttendance(\\''+uid+'\\',\\'present\\')">Present</button><button onclick="saveAttendance(\\''+uid+'\\',\\'late\\')">Late</button><button onclick="saveAttendance(\\''+uid+'\\',\\'absent\\')">Absent</button><button onclick="saveAttendance(\\''+uid+'\\',\\'excused\\')">Excused</button></div>')}
function saveAttendance(uid,status){state.attendance.push({id:id(),semesterId:state.activeSemesterId,unitId:uid,date:today(),status});save();closeModal();render();toast('Attendance saved')}
function addGrade(){openModal('Add assessment grade','<div class="form-grid">'+input('f_gname','Assessment name','text','')+select('f_gunit','Unit',units().map(u=>({value:u.id,label:u.name})),units()[0]?.id)+select('f_gtype','Type',['CAT','Assignment','Test','Exam','Project'],'CAT')+input('f_score','Score','number','')+input('f_max','Maximum','number','100')+'</div><button class="primary" onclick="saveGrade()">Save grade</button>')}
function saveGrade(){state.grades.push({id:id(),semesterId:state.activeSemesterId,name:$('#f_gname').value.trim(),unitId:$('#f_gunit').value,type:$('#f_gtype').value,score:Number($('#f_score').value),max:Number($('#f_max').value)||100});save();closeModal();render();toast('Grade saved')}
function deleteGrade(i){state.grades=state.grades.filter(x=>x.id!==i);save();render()}
function addSession(type){openModal('Log study session','<div class="form-grid">'+input('f_subject','Subject / topic','text','')+input('f_minutes','Minutes','number',type==='Focus'?25:45)+input('f_date','Date','date',today())+select('f_stype','Type',['Revision','Practice','Reading','Notes','Homework','Focus'],type||'Revision')+input('f_note','Note (optional)','text','')+'</div><button class="primary" onclick="saveSession()">Save session</button>')}
function saveSession(){const minutes=Number($('#f_minutes').value);if(!minutes||minutes<1)return;state.sessions.push({id:id(),semesterId:state.activeSemesterId,subject:$('#f_subject').value.trim()||'General study',minutes,date:$('#f_date').value,type:$('#f_stype').value,note:$('#f_note').value.trim()});save();closeModal();render();toast('Study session logged')}
function deleteSession(i){state.sessions=state.sessions.filter(x=>x.id!==i);save();render()}
function setFocus(m){if(focusTimer)return;focusRemaining=m*60;render()}
function toggleFocus(){if(focusTimer){clearInterval(focusTimer);focusTimer=null;render();return}focusTimer=setInterval(()=>{focusRemaining--;if(focusRemaining<=0){clearInterval(focusTimer);focusTimer=null;focusRemaining=25*60;save();notify('Focus block complete','Nice work. Log or review the session you just finished.');toast('Focus block complete')}render()},1000);render()}
function resetFocus(){if(focusTimer){clearInterval(focusTimer);focusTimer=null}focusRemaining=25*60;render()}
function addNote(n){n=n||{};openModal(n.id?'Edit note':'New note',input('f_ntitle','Title','text',n.title||'')+select('f_nunit','Unit',[{value:'',label:'General'},...units().map(u=>({value:u.id,label:u.name}))],n.unitId||'')+'<label>Note body<textarea id="f_nbody" rows="9">'+esc(n.body||'')+'</textarea></label><button class="primary" onclick="saveNote(\\''+(n.id||'')+'\\')">Save note</button>')}
function editNote(i){addNote(state.notes.find(n=>n.id===i))}
function saveNote(i){const data={id:i||id(),semesterId:state.activeSemesterId,title:$('#f_ntitle').value.trim(),unitId:$('#f_nunit').value,body:$('#f_nbody').value,updated:new Date().toISOString()};if(i)Object.assign(state.notes.find(n=>n.id===i),data);else state.notes.push(data);save();closeModal();render();toast('Note saved')}
function deleteNote(i){state.notes=state.notes.filter(x=>x.id!==i);save();render()}
function addResource(){openModal('Add resource',input('f_rtitle','Title','text','')+select('f_runit','Unit',[{value:'',label:'General'},...units().map(u=>({value:u.id,label:u.name}))],'')+select('f_rtype','Type',['Link','Video','Document','Reference'],'Link')+input('f_url','URL','url','https://')+'<button class="primary" onclick="saveResource()">Save resource</button>')}
function saveResource(){const url=$('#f_url').value.trim();if(!url)return;state.resources.push({id:id(),semesterId:state.activeSemesterId,title:$('#f_rtitle').value.trim()||url,unitId:$('#f_runit').value,type:$('#f_rtype').value,url});save();closeModal();render();toast('Resource saved')}
function deleteResource(i){state.resources=state.resources.filter(x=>x.id!==i);save();render()}
function addSemester(){openModal('Create semester',input('f_sname','Semester name','text','Semester 4')+input('f_syear','Academic year','text','2027')+input('f_sstart','Start date','date',today())+input('f_send','End date','date',today())+'<button class="primary" onclick="saveSemester()">Create semester</button>')}
function saveSemester(){const s={id:id(),name:$('#f_sname').value.trim(),year:$('#f_syear').value.trim(),start:$('#f_sstart').value,end:$('#f_send').value,status:'planned'};state.semesters.push(s);state.activeSemesterId=s.id;save();closeModal();render();toast('New semester created')}
function activateSemester(i){state.activeSemesterId=i;save();render();toast('Active semester changed')}
function addEvent(){openModal('Add calendar event',input('f_etitle','Event title','text','')+input('f_edate','Date','date',today())+select('f_etype','Type',['Event','Exam','Deadline','Study session'],'Event')+'<button class="primary" onclick="saveEvent()">Save event</button>')}
function saveEvent(){state.events.push({id:id(),semesterId:state.activeSemesterId,title:$('#f_etitle').value.trim(),date:$('#f_edate').value,type:$('#f_etype').value});save();closeModal();render()}
async function saveSettings(){state.profile.name=$('#p_name').value.trim();state.profile.institution=$('#p_inst').value.trim();state.profile.city=$('#p_city').value.trim();state.profile.program=$('#p_prog').value.trim();state.goals.weeklyMinutes=Math.max(1,Number($('#p_week').value)||300);state.goals.semesterTargetMinutes=Math.max(1,Number($('#p_sem').value)||7200);state.theme=$('#themeSetting').value;save();applyTheme();toast('Profile saved');render()}
async function handleProfilePhoto(e){const file=e.target.files?.[0];if(!file)return;try{state.profile.avatar=await resizeImage(file,320,0.82);save();render();toast('Profile photo saved')}catch{toast('Could not process image')}}
function resizeImage(file,maxSize,quality){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const scale=Math.min(1,maxSize/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext('2d');if(!ctx)return reject(new Error('canvas'));ctx.drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',quality))};img.src=reader.result}})}
function requestNotifications(){if(!('Notification'in window)){toast('Browser notifications unavailable');return}Notification.requestPermission().then(p=>{state.preferences.notifications=p==='granted';save();toast(p==='granted'?'Notifications enabled':'Permission not granted')})}
function notify(title,body){if(state.preferences.notifications&&'Notification'in window&&Notification.permission==='granted')new Notification(title,{body})}
function scheduleLessonReminder(){if(!state.preferences.notifications)return;const nl=nextLesson();if(!nl)return;const now=new Date(),target=new Date(now),[h,m]=nl.start.split(':').map(Number);target.setHours(h,m,0,0);const todayName=now.toLocaleDateString('en-US',{weekday:'long'});if(nl.day!==todayName)target.setDate(target.getDate()+((DAYS.indexOf(nl.day)-DAYS.indexOf(todayName)+7)%7));target.setMinutes(target.getMinutes()-Number(nl.reminder||state.preferences.reminderMinutes));const delay=target-now;if(delay>0&&delay<7*24*3600000)setTimeout(()=>{notify('Upcoming lesson',unitName(nl.unitId)+' starts at '+nl.start+' in '+nl.reminder+' minutes. Room '+(nl.room||'not set'));scheduleLessonReminder()},delay)}}
function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='study-tracker-backup.json';a.click();URL.revokeObjectURL(a.href)}
function importData(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=migrate(JSON.parse(r.result));save();render();toast('Backup imported')}catch{toast('Invalid backup file')}};r.readAsText(f)}
async function logout(){try{await fetch('/api/auth/logout',{method:'POST'});}catch{};window.__STUDY_USER__=null;state=null;localStorage.removeItem(storageKey());location.reload()}
function resetAll(){if(confirm('Reset all local data? This cannot be undone.')){localStorage.removeItem(storageKey());location.reload()}}
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
if(window.__STUDY_AUTH_READY__)initializeApp(window.__STUDY_STATE__||null);
